inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Include:
    - '**/*.rb'

  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'app/views/**/*'
    - 'node_modules/**/*'
    - 'front/**/*'
    - 'vendor/**/*'
    - 'Guardfile'
Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "**/*_spec.rb"
    - "**/*.rake"
    - "**/*.jbuilder"
    - "app/admin/**/*.rb"
    - "spec/support/shared_examples/**/*.rb"
    - "spec/factories/**.rb"
    - "spec/**/*_helper.rb"
