language: ruby
dist: trusty
rvm:
  - 2.5.3
env:
  - "rack=master"
before_install:
  - gem install bundler
install: 
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem update --system
  - gem install rails
script:
  - bundle exec install
  - bundle exec rails db:drop
  - bundle exec rails db:create
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails dev:setup RAILS_ENV=test
  - foreman start
  - bundle exec rspec