language: ruby
dist: trusty
rvm:
  - 2.5.3
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  - "rack=master"
before_install:
  - gem install bundler
install: 
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem update --system
  - gem install rails
  - bundle install
before_script:
  - psql -c "CREATE ROLE railsdb with createdb login password '123@456';" -U postgres
script:
  - rails db:drop
  - rails db:create
  - rails db:migrate RAILS_ENV=test
  - rails dev:setup RAILS_ENV=test
  - rspec