version: "3.8"

services:
  database:
    image: postgres:11.5
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/code:cached
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      RAILS_ENV: development
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: database
volumes:
  db_data:
