# PostgreSQL. Versions 9.1 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['BANK_API_DATABASE_USER'] %>
  password: <%= ENV['BANK_API_DATABASE_PASSWORD'] %>

default_local: &default_local
  host: localhost
  port: 5432

default_remote: &default_remote
  host: <%= ENV['BANK_API_DATABASE_HOST'] %>
  port: 5432

development:
  <<: *default
  <<: *default_local
  database: bank_api_development

test:
  <<: *default
  <<: *default_local
  database: bank_api_test


production:
  <<: *default
  <<: *default_remote
  database: bank_api_production
