# Generated by Django 3.1.4 on 2021-01-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('spent_limit', models.IntegerField(verbose_name='Limite de gastos')),
                ('number', models.IntegerField(verbose_name='Número do cartão')),
                ('expiration_date', models.DateField(verbose_name='Data de validade')),
                ('cvv_code', models.IntegerField(verbose_name='Código de Segurança')),
            ],
            options={
                'verbose_name_plural': 'Cartões de Crédito',
            },
        ),
    ]
