# Generated by Django 3.1.4 on 2021-01-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cc',
            name='name_flag',
            field=models.CharField(default='', max_length=100, verbose_name='Bandeira do cartão'),
        ),
    ]
